In [4]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

<center> 
<h1>Семинар №5</h1>
<br>
<h2>Математика в Python: math, random, numpy, scipy<h2>
<img src='http://www.thatcutesite.com/uploads/2011/03/cat_with_calculator-758x569.jpg' width=600>
</center>

## Немного о *float*
<img src="http://moda-svoimi-rukami.ru/wp-content/uploads/2016/07/funny-cat-foto-moment-15.jpg" width=400 align=left>

In [2]:
x = float("inf")
x > 1000
x > 1000 ** 6
x > x

x == 2 * x
1/x
x == x ** 2

True

True

False

True

0.0

True

In [3]:
x = float("-inf")
x < -1000
x < -(1000 ** 6)
x < x


x == 2 * x
1/x
x ** 2 == float("inf")

True

True

False

True

-0.0

True

In [4]:
1/0.0

ZeroDivisionError: float division by zero

In [5]:
x = float("nan")
print(x)

x == 2
x == x
x > 1
x < 1

nan


False

False

False

False

## Системы счисления

In [6]:
hex(10)
hex(16)
hex(1234)

bin(10)
bin(2)
bin(1234)

oct(10)
oct(8)
oct(1234)

'0xa'

'0x10'

'0x4d2'

'0b1010'

'0b10'

'0b10011010010'

'0o12'

'0o10'

'0o2322'

In [7]:
a = 0b1011001
a == 89
b = 0o1352
b == 746
c = 0xab4f
c == 43855

int('10011010010', 2)
int('2322', 8)
int('4d2', 16)
int('1234', 10)
int('1234')
int('14414', 5)

int('14415', 5)

True

True

True

1234

1234

1234

1234

1234

1234

ValueError: invalid literal for int() with base 5: '14415'

## Округление: бессмысленное и беспощадное
<img src='http://www.whycatwhy.com/wp-content/uploads/2016/03/round-cat-3-768x588.jpg' width=300>

In [8]:
round(1.23)
round(5.84)

round(0.16, 1)
round(10.72, 1)

round(12345, -1)
round(34222.2344, -3)

1

6

0.2

10.7

12340

34000.0

Не все так просто: банковское округление!
<img src='https://i.imgflip.com/19ga84.jpg' width=400>

In [9]:
round(2.65, 1)
round(2.75, 1)
round(2.85, 1)

2.6

2.8

2.9

## random

In [10]:
import random

random.random()  # [0, 1]
random.randint(12, 23)  # A <= x <= B
random.uniform(2.5, 7.8)  # min(a,b) <= x <= max(a,b)

0.5178219836660063

21

3.536606955037718

In [11]:
names =['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Isaac', 'Jack', 'Keith']

random.choice(names) 
random.sample(names, 5)
random.sample(names, 200)

'Frank'

['Grace', 'Frank', 'Jack', 'David', 'Isaac']

ValueError: Sample larger than population

In [12]:
prefix = names[:5]
prefix
random.shuffle(prefix)
prefix

['Alice', 'Bob', 'Charlie', 'David', 'Eve']

['Alice', 'Eve', 'Bob', 'Charlie', 'David']

In [13]:
random.normalvariate(0, 5)

1.7050364592830873

In [14]:
random.getrandbits(100)

1190298317782760205171056410525

In [15]:
import timeit 

timeit.timeit("random.getrandbits(100000)", setup="import random", number=20000)
timeit.timeit("random.randint(0, x)", setup="import random\nx=2**100000 - 1", number=20000)

0.5624829260050319

1.3653880939964438

## math   
Official docs: https://docs.python.org/3.6/library/math.html  
RUS: https://pythonworld.ru/moduli/modul-math.html  

In [16]:
import math

math.ceil(1.23)
math.ceil(5.84)
math.ceil(-2.4)
math.ceil(-3.7)

math.ceil(12.0)

2

6

-2

-3

12

In [17]:
math.floor(1.23)
math.floor(5.84)
math.floor(-2.4)
math.floor(-3.7)

math.floor(12.0)

1

5

-3

-4

12

In [18]:
int(1.23)
int(5.84)
int(-2.4)
int(-3.7)

int(12)

1

5

-2

-3

12

In [19]:
abs(3.54)
abs(-23.5)

abs(-2)
math.fabs(-2)

3.54

23.5

2

2.0

In [20]:
22 % 5
-22 % 7
33 % -23

12.34 % 2
4.76 % 1.311

math.fmod(22, 5)
math.fmod(-22, 7)
math.fmod(33, -23)
math.fmod(12.34, 2)
math.fmod(4.76, 1.311)

2

6

-13

0.33999999999999986

0.827

2.0

-1.0

10.0

0.33999999999999986

0.827

## sum vs math.fsum 

In [21]:
arr = [1, 1e100, 1, -1e100]
sum(arr)
math.fsum(arr)

0.0

2.0

Мораль: для больших массивов разных чисел с плавающей точкой используйте **math.fsum**!  
More: https://code.activestate.com/recipes/393090/
<img src='http://superwall.us/wallpaper/an_equation_cat_face_symbols_fish_abstract-oDvK.jpg' width=400>

In [22]:
math.exp(2.4) 
math.log(2.4) 
math.log2(2.4) 
math.log10(2.4) 
math.pow(2.4, 3.6) 

11.023176380641601

0.8754687373538999

1.263034405833794

0.38021124171160603

23.37547637097492

In [23]:
math.pi
math.e
math.sqrt(2.4) 
math.sin(2*math.pi) 
math.cos(math.pi) 
math.tan(0) 

math.asin(0.5) / math.pi
math.acos(0.5) / math.pi

math.degrees(math.pi) 
math.radians(60)

3.141592653589793

2.718281828459045

1.5491933384829668

-2.4492935982947064e-16

-1.0

0.0

0.16666666666666669

0.33333333333333337

180.0

1.0471975511965976

In [24]:
math.gcd(25, 10)
math.gcd(24, 35)

5

1

## numpy
http://www.numpy.org/

In [5]:
import numpy as np

vec = np.array([1,2,3,4])
vec
type(vec)
vec.dtype
vec.shape
vec.size

array([1, 2, 3, 4])

numpy.ndarray

dtype('int64')

(4,)

4

In [26]:
MX = np.array([[1, None], [3, 4]], dtype=float)
MX
type(MX)
MX.dtype
MX.shape
MX.size

array([[ 1., nan],
       [ 3.,  4.]])

numpy.ndarray

dtype('float64')

(2, 2)

4

In [27]:
vec[1] = 5.4
vec
vec[2] = '6'
vec
MX[0][0] = '12'
MX
MX[0][1] = 'abc'

array([1, 5, 3, 4])

array([1, 5, 6, 4])

array([[12., nan],
       [ 3.,  4.]])

ValueError: could not convert string to float: 'abc'

In [28]:
np.arange(0, 10, 2)
np.arange(-1, 1, 1/3)
np.linspace(-1, 1, 11)
np.logspace(1, 4, 5, base=2)
2 ** np.linspace(1, 4, 5)

array([0, 2, 4, 6, 8])

array([-1.00000000e+00, -6.66666667e-01, -3.33333333e-01, -2.22044605e-16,
        3.33333333e-01,  6.66666667e-01])

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

array([ 2.        ,  3.36358566,  5.65685425,  9.51365692, 16.        ])

array([ 2.        ,  3.36358566,  5.65685425,  9.51365692, 16.        ])

In [29]:
np.random.random((4, 5))

array([[0.01449052, 0.75388337, 0.83839295, 0.93261902, 0.86720585],
       [0.01305722, 0.24673682, 0.41038166, 0.26238751, 0.35665049],
       [0.71288554, 0.82171078, 0.99165032, 0.06039515, 0.12608095],
       [0.63937672, 0.96952839, 0.28544296, 0.23115559, 0.96322594]])

In [6]:
np.mgrid[0:5,0:5]
np.mgrid[0:13:2, 0:25:3]
np.mgrid[0:3, 1:4, 2:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

array([[[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4],
        [ 6,  6,  6,  6,  6,  6,  6,  6,  6],
        [ 8,  8,  8,  8,  8,  8,  8,  8,  8],
        [10, 10, 10, 10, 10, 10, 10, 10, 10],
        [12, 12, 12, 12, 12, 12, 12, 12, 12]],

       [[ 0,  3,  6,  9, 12, 15, 18, 21, 24],
        [ 0,  3,  6,  9, 12, 15, 18, 21, 24],
        [ 0,  3,  6,  9, 12, 15, 18, 21, 24],
        [ 0,  3,  6,  9, 12, 15, 18, 21, 24],
        [ 0,  3,  6,  9, 12, 15, 18, 21, 24],
        [ 0,  3,  6,  9, 12, 15, 18, 21, 24],
        [ 0,  3,  6,  9, 12, 15, 18, 21, 24]]])

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]]],


       [[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]],

        [[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]],

        [[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]],


       [[[2, 3, 4],
         [2, 3, 4],
         [2, 3, 4]],

        [[2, 3, 4],
         [2, 3, 4],
         [2, 3, 4]],

        [[2, 3, 4],
         [2, 3, 4],
         [2, 3, 4]]]])

In [31]:
np.diag([1,2,3,4])

np.diag([1, -1, 1, -1], k=-1)

np.diag([[1,2,3],
         [4,5,6],
         [7,8,9]],k=1)

np.zeros((4,3))
np.ones((4,3))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

array([[ 0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0],
       [ 0,  0,  1,  0,  0],
       [ 0,  0,  0, -1,  0]])

array([2, 6])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
MX = np.arange(16).reshape(4,4)
MX

np.arange(16).reshape(2, 2, 4)

np.arange(16).reshape(2, -1)
np.arange(16).reshape(-1, 2)

np.arange(16).reshape(5, 3)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

ValueError: cannot reshape array of size 16 into shape (5,3)

In [33]:
MX
MX[1:3, -2:]
MX[:,0]
MX[::2,0]
MX[1::2,0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[ 6,  7],
       [10, 11]])

array([ 0,  4,  8, 12])

array([0, 8])

array([ 4, 12])

In [34]:
MX[[0,2,3],:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
mask = (MX % 2 == 0)
mask
indices = np.where(mask)
indices
MX[indices[0], indices[1]]

# Короче
MX[MX % 2 == 0]

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

(array([0, 0, 1, 1, 2, 2, 3, 3]), array([0, 2, 0, 2, 0, 2, 0, 2]))

array([ 0,  2,  4,  6,  8, 10, 12, 14])

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [36]:
v = np.array([1, 2, 3, 4, 5, 6])

v + 2
v * 2
v / 2
v ** 2
v * v

array([3, 4, 5, 6, 7, 8])

array([ 2,  4,  6,  8, 10, 12])

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

array([ 1,  4,  9, 16, 25, 36])

array([ 1,  4,  9, 16, 25, 36])

In [37]:
2 ** (v + 3)
np.exp(v)
np.log(v)
np.log1p(v)

array([ 16,  32,  64, 128, 256, 512])

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947,
       1.94591015])

In [38]:
A = np.arange(12).reshape(3,-1) % 3
A

A.T

array([[0, 1, 2, 0],
       [1, 2, 0, 1],
       [2, 0, 1, 2]])

array([[0, 1, 2],
       [1, 2, 0],
       [2, 0, 1],
       [0, 1, 2]])

In [39]:
C = A + 1
C

A * C
A ** C

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3]])

array([[0, 2, 6, 0],
       [2, 6, 0, 2],
       [6, 0, 2, 6]])

array([[0, 1, 8, 0],
       [1, 8, 0, 1],
       [8, 0, 1, 8]])

In [40]:
B = np.arange(8).reshape(4,-1)
B

A.dot(B)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

array([[10, 13],
       [10, 14],
       [16, 21]])

In [41]:
D = 0.1 * np.diag(np.ones(3))
D

np.linalg.inv(D)

array([[0.1, 0. , 0. ],
       [0. , 0.1, 0. ],
       [0. , 0. , 0.1]])

array([[10.,  0.,  0.],
       [ 0., 10.,  0.],
       [ 0.,  0., 10.]])

In [42]:
A = np.arange(12).reshape(4,-1) ** 2
A

np.mean(A, axis=0)
np.std(A, axis=1)

A.trace()
np.sum(np.diag(A))

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

array([31.5, 41.5, 53.5])

array([ 1.69967317,  6.5489609 , 11.4406682 , 16.33673434])

80

80

In [43]:
v = np.arange(10) % 2
v
v.shape
v.T
v.T.shape

v[np.newaxis]
v[np.newaxis].shape

v = v.reshape(1, *v.shape)
v.shape
v

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

(10,)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

(10,)

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

(1, 10)

(1, 10)

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

In [44]:
np.unique(v)

array([0, 1])

In [45]:
x = np.vstack((v,v))
x
x.shape

y = np.hstack((v,v))
y
y.shape

z = np.stack((v,v))
z
z.shape

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

(2, 10)

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

(1, 20)

array([[[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]],

       [[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]]])

(2, 1, 10)

In [46]:
def vectorMul(k, x):
    # x is some vector
    return x * k

vectorized = np.vectorize(vectorMul, excluded=['x'], otypes=[np.ndarray])
vectorized(k=np.array([1,3]), x=np.arange(3))

array([array([0, 1, 2]), array([0, 3, 6])], dtype=object)

## Насколько лучше использовать C/C++ для ресурсоемких расчетов

Умножение вектора

In [47]:
def numpyMul(v):
    return v * 2

def pythonMul(v):
    return [x * 2 for x in v]

v = np.arange(10000)
timeit.timeit("numpyMul(v)", setup="from __main__ import numpyMul, v", number=1000)
timeit.timeit("pythonMul(v)", setup="from __main__ import pythonMul, v", number=1000)

v = [i for i in range(10000)]
timeit.timeit("pythonMul(v)", setup="from __main__ import pythonMul, v", number=1000)

0.013164643998607062

2.135799825999129

0.4892183190022479

Сложение

In [48]:
v = np.arange(10000)
timeit.timeit("v.sum()", setup="from __main__ import v", number=1000)

v = [i for i in range(10000)]
timeit.timeit("sum(v)", setup="from __main__ import v", number=1000)


0.01135477200296009

0.08728817700466607

Умножение матриц

In [49]:
def numpyMatMul(A, B):
    return A.dot(B)

def pythonMatMul(A, B):
    res = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(A[0])):
                res[i][j] += A[i][k] * B[k][j]
    return res

A = np.random.rand(50, 100)
B = np.random.rand(100, 20)

timeit.timeit("numpyMatMul(A, B)", setup="from __main__ import numpyMatMul, A, B", 
                   number=100)

timeit.timeit("pythonMatMul(A, B)", setup="from __main__ import pythonMatMul, A, B", 
                   number=100)

A = list(map(list, A))
B = list(map(list, B))
timeit.timeit("pythonMatMul(A, B)", setup="from __main__ import pythonMatMul, A, B", 
                   number=100)

0.002686209001694806

6.43668865699874

2.6272269649998634

## scipy

In [5]:
from scipy import integrate
import math

def f(args):
    return 1

integrate.quad(f, 0, 4.5)[0]

4.5

In [51]:
from scipy import optimize

def f(args):
    x, y = args
    return (x - 2*y)**2 + (x / y) + 16 * math.exp(x * y)

optimize.minimize(f, [0.1, 2.5])

      fun: 13.148883663068478
 hess_inv: array([[0.02000526, 0.00074804],
       [0.00074804, 0.09574759]])
      jac: array([4.37423861, 2.29439616])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 391
      nit: 2
     njev: 96
   status: 2
  success: False
        x: array([-0.66458708,  0.61853195])

In [52]:
from scipy import linalg
    
A = np.random.randint(10, size=(5, 5))
A
b = np.arange(3, 12, 2).reshape(1, -1).T
b

x = linalg.solve(A, b)
x
A.dot(x)

array([[5, 9, 2, 5, 0],
       [5, 6, 8, 6, 4],
       [2, 5, 9, 7, 7],
       [9, 5, 3, 0, 1],
       [8, 4, 5, 2, 2]])

array([[ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]])

array([[ 3.30152144],
       [-2.58782849],
       [-3.65283541],
       [ 3.41770401],
       [ 3.18395574]])

array([[ 3.],
       [ 5.],
       [ 7.],
       [ 9.],
       [11.]])

In [53]:
linalg.det(A)

723.0

In [54]:
e_vals, e_vecs = linalg.eig(A)

e_vals
e_vecs

e_val0 = e_vals[0]
e_vec0 = e_vecs[:, 0]

e_val0
e_vec0

A.dot(e_vec0) - e_val0 * e_vec0

array([24.48853963+0.        j, -4.55476762+0.        j,
        1.64041146+1.62659485j,  1.64041146-1.62659485j,
       -1.21459494+0.        j])

array([[ 0.38939796+0.        j, -0.17721752+0.        j,
        -0.43746487-0.02510814j, -0.43746487+0.02510814j,
        -0.24479639+0.        j],
       [ 0.53497283+0.        j, -0.07002308+0.        j,
         0.2884147 -0.11254383j,  0.2884147 +0.11254383j,
         0.55310535+0.        j],
       [ 0.54875101+0.        j, -0.53735824+0.        j,
         0.62486663+0.        j,  0.62486663-0.        j,
        -0.0610821 +0.        j],
       [ 0.33530803+0.        j,  0.67963928+0.        j,
        -0.46698455+0.07713388j, -0.46698455-0.07713388j,
        -0.66689471+0.        j],
       [ 0.38550507+0.        j,  0.4615488 +0.        j,
        -0.27100187+0.15562902j, -0.27100187-0.15562902j,
         0.43089399+0.        j]])

(24.488539630042542+0j)

array([0.38939796+0.j, 0.53497283+0.j, 0.54875101+0.j, 0.33530803+0.j,
       0.38550507+0.j])

array([-7.10542736e-15+0.j, -1.59872116e-14+0.j, -3.55271368e-15+0.j,
       -1.06581410e-14+0.j, -1.24344979e-14+0.j])